version: '3.3'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:  

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: icgrem/foodgram:latest
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:4000
    volumes:
      - staticfiles:/code/static/
      - mediafiles:/code/media/
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/code/static/
      - mediafiles:/code/media/
    ports:
      - "8080:80"
    depends_on:
      - web
