version: '3.3'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:  

services:
  db:
    image: postgres:latest
    # не могу исправить, тесты требуют latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/code/static/
      - mediafiles:/code/media/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0
    volumes:
      - staticfiles:/code/static/
      - mediafiles:/code/media/
    ports:
      - "81:80"
    depends_on:
      - web
