version: '3.9'

volumes:
  food_postgres_data:
  food_staticfiles:
  food_mediafiles:

services:
  food_db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - food_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGGSSENCMODE=disable

  food_web:
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:4000
    volumes:
      - food_staticfiles:/code/static/
      - food_mediafiles:/code/media/
    ports:
      - 4000:4000 
    depends_on:
      - food_db
    env_file:
      - ./.env

  food_nginx:
    build: ./nginx
    restart: always
    volumes:
      - food_staticfiles:/code/static/
      - food_mediafiles:/code/media/
    ports:
      - "8080:80"
    depends_on:
      - food_web
