# Generated by Django 3.1.2 on 2020-10-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201009_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_quantity', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], max_length=10),
        ),
    ]
