# Generated by Django 3.1.2 on 2020-10-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20201019_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default/default_img.jpg', upload_to='recipe/'),
        ),
    ]
