# Generated by Django 3.1.2 on 2020-10-20 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_auto_20201020_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('shopper', 'recipe')},
        ),
    ]
