# Generated by Django 3.1.2 on 2020-10-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20201022_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingredient',
            new_name='RecipeIngredient',
        ),
    ]
