# Generated by Django 3.1.2 on 2020-10-20 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_auto_20201020_1107'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorit',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorit', to='recipe.recipe'),
        ),
    ]
