# Generated by Django 3.1.2 on 2020-10-20 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_auto_20201020_1410'),
        ('social', '0002_auto_20201020_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorit',
            unique_together={('author', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
    ]
