name: foodgram-workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r foodgram/requirements.txt
    - name: Lint with flake8
      run: flake8 --ignore=E501,F401,F403,F405 .
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        path: ./foodgram
        dockerfile: {path}/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: icgrem/foodgram
        tag_with_ref: true
  send_message:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: $Свежий {{ github.workflow }} залит на DockerHub!
